openapi: 3.0.0
info:
  description: |
    This is a sample app server
  version: "1.0.0"
  title: Sample App
  contact:
    email: maxim.baranov@simbirsoft.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/api/healthz':
    get:
      summary: health check
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
        '503':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
  '/api/upload/{path}':
    get:
      summary: Get advertisement image
      responses:
        '200':
          description: successful operation
  '/api/advertisement':
    get:
      summary: Get all advertisements
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Advertisement'
    post:
      summary: Place/update advertisement
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Advertisement'
        '400':
          description: Validation error
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                image:
                  type: string
                  format: binary
        description: order placed for purchasing the pet
        required: true
  '/api/advertisement/{advertisementId}':
    get:
      summary: Find advertisement by ID
      parameters:
        - name: advertisementId
          in: path
          description: ID of the advertisement
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Advertisement'
    delete:
      summary: Delete advertisement by ID
      parameters:
        - name: advertisementId
          in: path
          description: ID of the advertisement
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Advertisement'

components:
  schemas:
    Advertisement:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        image:
          type: string
    Health:
      type: object
      properties:
        healthy:
          type: string
