"""empty message

Revision ID: 2a18f4506ad1
Revises: 194b413f0417
Create Date: 2019-12-25 21:10:59.091942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a18f4506ad1'
down_revision = '194b413f0417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisement_id'), 'advertisement', ['id'], unique=True)
    op.create_index(op.f('ix_advertisement_title'), 'advertisement', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisement_title'), table_name='advertisement')
    op.drop_index(op.f('ix_advertisement_id'), table_name='advertisement')
    op.drop_table('advertisement')
    # ### end Alembic commands ###
